version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/codearena?sslmode=disable

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: codearena
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
